import type { ReferenceEntry } from "./historical-reference-panel";

export interface ReferencePanelElements { prompt:HTMLElement; open:HTMLButtonElement; status:HTMLElement; dialog:HTMLDialogElement; title:HTMLElement; date:HTMLElement; warning:HTMLElement; description:HTMLElement; viewport:HTMLElement; image:HTMLImageElement; imageStatus:HTMLElement; zoomOut:HTMLButtonElement; zoomIn:HTMLButtonElement; zoomReset:HTMLButtonElement; zoomStatus:HTMLElement; source:HTMLAnchorElement; license:HTMLAnchorElement; attribution:HTMLElement; disclosure:HTMLElement; close:HTMLButtonElement }
export class HistoricalReferencePanelController {
  private entry:ReferenceEntry|null=null; private scaleIndex=0; private readonly scales=[1,1.5,2];
  constructor(private readonly el:ReferencePanelElements){el.open.addEventListener("click",()=>this.open());el.close.addEventListener("click",()=>el.dialog.close());el.dialog.addEventListener("keydown",(event)=>{if(event.key==="Escape"&&el.dialog.open){event.preventDefault();el.dialog.close();}});el.dialog.addEventListener("close",()=>{el.open.setAttribute("aria-expanded","false");el.open.focus();});el.image.addEventListener("load",()=>{el.imageStatus.textContent="画像を読み込みました。";});el.image.addEventListener("error",()=>{el.imageStatus.textContent="画像を読み込めませんでした。地図や出典は引き続き利用できます。";});el.zoomIn.addEventListener("click",()=>this.zoom(1));el.zoomOut.addEventListener("click",()=>this.zoom(-1));el.zoomReset.addEventListener("click",()=>{this.scaleIndex=0;this.applyZoom();});}
  setEntry(entry:ReferenceEntry|null):void {this.entry=entry;this.el.prompt.hidden=!entry;this.el.open.tabIndex=entry?0:-1;if(entry){const year=entry.sourceDateDisplayJa.match(/（(\d{4})）/u)?.[1]??entry.sourceDateDisplayJa;this.el.open.textContent=`${year}年の和田倉御門図を見る`;this.el.open.setAttribute("aria-expanded",String(this.el.dialog.open));}else if(this.el.dialog.open)this.el.dialog.close();}
  private open():void {const e=this.entry;if(!e||this.el.dialog.open)return;this.el.title.textContent=e.titleJa;this.el.date.textContent=`${e.sourceDateDisplayJa}・${e.historicalPeriodJa}`;this.el.warning.textContent=e.cautionJa;this.el.description.textContent=e.descriptionJa;this.el.attribution.textContent=`出典: ${e.attributionJa}`;this.el.disclosure.textContent=e.derivativeDisclosureJa.replace(/行った。$/u,"行いました。");this.el.source.href=e.sourceUrl;this.el.license.href=e.licenseUrl;this.el.image.alt=e.altJa;this.el.image.width=e.image.width;this.el.image.height=e.image.height;if(!this.el.image.getAttribute("src")){this.el.image.src=`${import.meta.env.BASE_URL}${e.image.publicPath.replace(/^\//u,"")}`;}this.el.open.setAttribute("aria-expanded","true");this.el.dialog.showModal();}
  private zoom(delta:number):void{this.scaleIndex=Math.max(0,Math.min(this.scales.length-1,this.scaleIndex+delta));this.applyZoom();}
  private applyZoom():void{const scale=this.scales[this.scaleIndex]!;this.el.image.style.width=`${scale*100}%`;this.el.image.style.maxWidth=scale===1?"100%":"none";this.el.zoomStatus.textContent=scale===1?"全体表示":`${scale*100}%`;this.el.zoomOut.disabled=this.scaleIndex===0;this.el.zoomIn.disabled=this.scaleIndex===this.scales.length-1;}
  dispose():void{if(this.el.dialog.open)this.el.dialog.close();}
}
