import type { HistoricalRasterGeoreferenceMethod } from "./historical-raster";
export type HistoricalRasterControlPointRole = "transform" | "validation" | "hold" | "rejected";
export type HistoricalRasterControlPointFeatureType = "castle-gate" | "moat-corner" | "bridge" | "temple" | "shrine" | "stone-wall" | "river-junction" | "road-junction" | "other";
export interface HistoricalRasterControlPoint { readonly id: string; readonly role: HistoricalRasterControlPointRole; readonly pixelX: number; readonly pixelY: number; readonly latitude: number; readonly longitude: number; readonly historicalLabelJa: string; readonly modernLabelJa: string; readonly featureType: HistoricalRasterControlPointFeatureType; readonly basisJa: string; readonly confidence: "high" | "medium" | "low"; readonly currentExistence: "extant" | "archaeological-remains" | "officially-located-lost-site" | "uncertain"; readonly movedStatus: "not-moved" | "possibly-moved" | "moved" | "unknown"; readonly sourceIds: readonly string[]; readonly evidenceUrls: readonly string[]; readonly rejectionReasonJa?: string; }
export interface HistoricalRasterControlPoints { readonly schemaVersion: 2; readonly rasterId: string; readonly imageWidth: number; readonly imageHeight: number; readonly points: readonly HistoricalRasterControlPoint[]; }
export interface HistoricalRasterGeoreferenceV1 { readonly schemaVersion: 1; readonly rasterId: string; readonly method: HistoricalRasterGeoreferenceMethod; readonly controlPointCount: number; readonly software: string; readonly softwareVersion: string; readonly meanErrorMeters: number | null; readonly medianErrorMeters: number | null; readonly maximumErrorMeters: number | null; readonly geographicCoverageJa: string; readonly distortionNoteJa: string; readonly adjacentSheetNoteJa: string; readonly controlPointsSha256: string; readonly transformationParametersSha256: string; }
export interface HistoricalRasterGeoreference extends Omit<HistoricalRasterGeoreferenceV1, "schemaVersion"> { readonly schemaVersion: 2; readonly validationPointCount: number; readonly validationMeanErrorMeters: number; readonly validationMedianErrorMeters: number; readonly validationP90ErrorMeters: number; readonly validationMaximumErrorMeters: number; readonly qualityGateVersion: 1; readonly qualityGatePassed: boolean; }
export interface HistoricalRasterResidual { readonly role: HistoricalRasterControlPointRole; readonly expected: { readonly latitude: number; readonly longitude: number }; readonly actual: { readonly latitude: number; readonly longitude: number }; }
export const HISTORICAL_RASTER_CONTROL_POINT_SCHEMA_VERSION: 2;
export const HISTORICAL_RASTER_GEOREFERENCE_SCHEMA_VERSION: 2;
export const HISTORICAL_RASTER_QUALITY_GATE_VERSION: 1;
export const HISTORICAL_RASTER_CONTROL_POINT_CONFIDENCES: readonly ["high", "medium", "low"];
export const HISTORICAL_RASTER_CONTROL_POINT_ROLES: readonly HistoricalRasterControlPointRole[];
export function migrateHistoricalRasterControlPointsV1(input: unknown): unknown;
export function validateHistoricalRasterControlPoints(input: unknown, options?: { approvedSourceIds?: readonly string[] }): Readonly<HistoricalRasterControlPoints>;
export function hasDistributedControlPoints(controlPoints: HistoricalRasterControlPoints, role?: HistoricalRasterControlPointRole): boolean;
export function greatCircleDistanceMeters(left: { latitude: number; longitude: number }, right: { latitude: number; longitude: number }): number;
export function summarizeResidualMeters(values: readonly number[]): Readonly<{ count: number; mean: number; median: number; p90: number; maximum: number; values: readonly number[] }>;
export function summarizeValidationResiduals(residuals: readonly HistoricalRasterResidual[]): ReturnType<typeof summarizeResidualMeters>;
export function evaluateHistoricalRasterQualityGate(input: { rightsApproved: boolean; commercialUseCompatible: boolean; attributionComplete: boolean; transformPointCount: number; validationPointCount: number; transformDistributed: boolean; validationDistributed: boolean; validationMeanErrorMeters: number; validationMedianErrorMeters: number; validationMaximumErrorMeters: number; visualIntegrityPassed: boolean; textReadable: boolean; boundsConfirmed: boolean; totalTileBytes: number; packageVerified: boolean }): Readonly<{ qualityGateVersion: 1; passed: boolean; failures: readonly string[] }>;
export function validateHistoricalRasterGeoreference(input: unknown): Readonly<HistoricalRasterGeoreference | HistoricalRasterGeoreferenceV1>;
